#!/bin/bash
# Bash Cheatsheet: https://devhints.io/bash
source "${0%/*}/src/core.sh";
BIN="${0%/*}"

# Flags
# NOTE: if a flag takes an argument you need to `shift 2`, otherwise just `shift`
# =====================================================================================================================

PARAMS=""
while (( "$#" )); do case "$1" in
  --)
    shift
    break
    ;;
  -*|--*)
    echo "Error: Unsupported flag $1" >&2
    exit 1
    ;;
  *)
    PARAMS="$PARAMS $1"
    shift
    ;;
esac; done
eval set -- "$PARAMS"

# Logic
# =====================================================================================================================

case "$1" in
  meta)
    echo "OS=$OS"
    echo "BROWSER=$BROWSER"
    echo "CLIPBOARD=$CLIPBOARD"
    ;;
  src)
    "$VISUAL" "$BIN"
    ;;
  remove) rm -rf "$BIN/.bins/$2";;
  show|view) ls "$BIN/.bins";;
  edit|create)
    [ -e "$BIN/.bins/" ] || mkdir -p "$BIN/.bins/"
    if [ -z "$1" ]; then
      "$VISUAL" "$BIN/.bins/"
    else
      [ -f "$BIN/.bins/$2" ] || {
        cp "$BIN/src/bin.tmpl" "$BIN/.bins/$2"
        chmod +x "$BIN/.bins/$2"
      }
      "$VISUAL" "$BIN/.bins/$2"
    fi
    ;;
  *) echo "that did nothing. nothing was done";;
esac
