#!/bin/bash
# Bash Cheatsheet: https://devhints.io/bash

ROOT="${0%/*}"

case "$(uname -a)" in
  Darwin*) OS="Darwin";;
  Linux*)
    OS="Linux"
    grep -q Microsoft /proc/version \
      && OS="WSL"
    ;;
esac

case "$OS" in
  WSL)
    CHROME="/c/Program Files (x86)/Google/Chrome/Application/chrome.exe"
    CLIPBOARD="clip.exe"
    ;;
  Darwin)
    CLIPBOARD="open -a 'Google Chrome'"
    COPY="pbcopy"
    ;;
esac

clip() {
  [[ -z "$CLIPBOARD" ]] && \
    echo "no \$CLIPBOARD available"; exit 1
  "$COPY" < "$1"
}

chrome_open_url() {
  [[ -z "$CHROME" ]] && \
    echo "no \$CHROME available"; exit 1
  "$CHROME" "$1"
}

# Flags
# NOTE: if a flag takes an argument you need to `shift 2`, otherwise just `shift`
# =====================================================================================================================

PARAMS=""
while (( "$#" )); do case "$1" in
  --to)
    NAME="$2"
    shift 2
    break
    ;;
  --)
    shift
    break
    ;;
  -*|--*)
    echo "Error: Unsupported flag $1" >&2
    exit 1
    ;;
  *)
    PARAMS="$PARAMS $1"
    shift
    ;;
esac; done
eval set -- "$PARAMS"

# Logic
# =====================================================================================================================

# If --to isn't passed, then default to $USER
NAME="${NAME:=$USER}"

case "$1" in
  hello) source "$ROOT/src/hello.sh" "$NAME";;
  # if no arguments are passed, ask what to say
  *)
    echo "What should I say?"
    echo -n "> "
    read -r repeat
    echo "Hmm..."
    sleep 1
    echo "I think I can handle that!"
    sleep 2
    echo
    echo "$repeat"
esac
