#!/bin/bash
export VIRO_HOME="${VIRO_HOME:-"$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"}"
source "$VIRO_HOME/src/utils.sh"

PARAMS=""
while (( "$#" )); do case "$1" in
  -h|--help) man viro && exit 0;;

  --) shift && break;;
  -*|--*) log "Error: Unsupported flag $1" >&2 && exit 1;;
  *) PARAMS="$PARAMS $1" && shift;;
esac; done
eval set -- "$PARAMS"

case "$1" in
  env) "$VIRO_HOME/src/core/env.sh" "${@:2}";;
  path) "$VIRO_HOME/src/core/path.sh" "${@:2}";;
  alias) "$VIRO_HOME/src/core/alias.sh" "${@:2}";;
  boot) "$VISUAL" "$VIRO_HOME/user/boot.sh" && refresh;;
  install)
    log "two lines will be added to your .bashrc file:"
    log "   at the top: the path to your viro installation will be exported as \$VIRO_HOME"
    log "   at the bottom: viro core will be sourced"
    log
    if yorn "Continue?"; then
      sed -i -e '/VIRO_HOME/d' -e "1i export VIRO_HOME=\"$VIRO_HOME\"" "$HOME/.bashrc"
      echo "source \"\$VIRO_HOME/src/core.sh\"" >> "$HOME/.bashrc"
      refresh
    else
      log "Maybe make a backup first?"
      log "try: mv $HOME/.bashrc $HOME/.bashrc.bak"
    fi
    ;;
esac
