#!/bin/bash
export VIRO_HOME="${VIRO_HOME:-"$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"}"
source "$VIRO_HOME/src/utils.sh"

PARAMS=""
while (( "$#" )); do case "$1" in
  -h|--help) man viro && exit 0;;
  --yes|-y|--force|-f) YES="y" && shift;;

  --) shift && break;;
  -*|--*) log "Error: Unsupported flag $1" >&2 && exit 1;;
  *) PARAMS="$PARAMS $1" && shift;;
esac; done
eval set -- "$PARAMS"

case "$1" in
  bin) YES="$YES" source "$VIRO_HOME/src/bin.sh" "${@:2}";;
  env) YES="$YES" source "$VIRO_HOME/src/env.sh" "${@:2}";;
  path) source "$VIRO_HOME/src/path.sh" "${@:2}";;
  alias) YES="$YES" source "$VIRO_HOME/src/alias.sh" "${@:2}";;
  boot) "$VISUAL" source "$VIRO_HOME/user/boot.sh" && refresh;;
  install)
    [[ -n "$YES" ]] || {
      log "two lines will be added to your .bashrc file:"
      log "   at the top: the path to your viro installation will be exported as \$VIRO_HOME"
      log "   at the bottom: viro core will be sourced"
    }
    if [[ -n "$YES" ]] || yorn "Continue?"; then
      sed -i '/VIRO_HOME/d' "$HOME/.bashrc"
      echo "source \"\$VIRO_HOME/src/core.sh\"" >> "$HOME/.bashrc"
      sed -i "1i export VIRO_HOME=\"$VIRO_HOME\"" "$HOME/.bashrc"
      refresh
    else
      log "Maybe make a backup first?"
      log "try: mv $HOME/.bashrc $HOME/.bashrc.bak"
    fi
    ;;
esac
