#!/bin/bash
source "$VIRO_HOME/src/utils.sh"

ALIEN="$VIRO_HOME/user/aliases"

# Flags
# NOTE: if a flag takes an argument you need to `shift 2`, otherwise just `shift`
# =====================================================================================================================
PARAMS=""
while (( "$#" )); do case "$1" in
  -h|--help) man "${BASH_SOURCE[0]}" && exit 0;;
  --secret) ALIEN="$VIRO_HOME/user/secret_aliases" && shift;;

  --) shift && break;;
  -*|--*) log "Error: Unsupported flag $1" >&2 && exit 1;;
  *) PARAMS="$PARAMS $1" && shift;;
esac; done
eval set -- "$PARAMS"

mkdir -p "$(dirname "$ALIEN")" && touch "$ALIEN"
case "$1" in
  ls) sed -e "s/=/~/" -e "s/alias //" -e "s/'//g" < "$ALIEN" | column -t -s~;;
  add)
    name="${2:-"$(prompt "name:")"}"
    cmd="${cmd:-"${@:3}"}"
    echo "$cmd"
    cmd="${cmd:-"$(prompt "alien add $name:")"}"
    sed -i "/$name=/d" "$ALIEN"
    echo "alias $name=\"$cmd\"" >> "$ALIEN"
    log "added: $(grep "alias $name" "$ALIEN")"
    viro refresh
    ;;
  edit) "$VISUAL" "$ALIEN" && viro refresh;;
  rm)
    name="${2:-"$(sed -e 's/=./ /' < "$ALIEN" | awk '{print $2}' | choose)"}"
    [[ -z "$name" ]] && log "No aliases have been removed" && exit 1
    log "removed: $(grep "alias $name" "$ALIEN")"
    sed -i "/$name=/d" "$ALIEN"
    viro refresh
    ;;
  has) alien ls | grep -wq "$2";;
esac
