#!/bin/bash
# Bash Cheatsheet: https://devhints.io/bash
BIN="$( ( cd ../ && dirname "${0%/*}" ) )";
source "$BIN/src/core.sh"

# Flags
# NOTE: if a flag takes an argument you need to `shift 2`, otherwise just `shift`
# =====================================================================================================================

PARAMS=""
while (( "$#" )); do case "$1" in
  --)
    shift
    break
    ;;
  -*|--*)
    echo "Error: Unsupported flag $1" >&2
    exit 1
    ;;
  *)
    PARAMS="$PARAMS $1"
    shift
    ;;
esac; done
eval set -- "$PARAMS"

# Logic
# =====================================================================================================================

case "$1" in
  meta)
    echo "BIN=$BIN"
    echo "OS=$OS"
    echo "DISTRO=$DISTRO"
    echo "BROWSER=$BROWSER"
    echo "CLIPBOARD=$CLIPBOARD"
    ;;
  src)
    if [ -z "$1" ]; then
      "$VISUAL" "$BIN/src/"
    else
      "$VISUAL" "$BIN/src/$2.sh"
    fi
    ;;
  remove) rm -rf "$BIN/bins/$2";;
  show|view) ls "$BIN/bins";;
  rename) mv "$BIN/bins/$2" "$BIN/bins/$3";;
  enter) cd "$BIN";;
  edit|create)
    if [ -z "$1" ]; then
      "$VISUAL" "$BIN/bins/"
    else
      [ -x "$BIN/bins/$2" ] || {
        cp "$BIN/bin.tmpl" "$BIN/bins/$2"
        chmod +x "$BIN/bins/$2"
      }
      "$VISUAL" "$BIN/bins/$2"
    fi
    ;;
  branch) (cd "$BIN" && git checkout "$2");;
  commit) (cd "$BIN" && git add -A . && git commit -m "bin commit");;
  push) (cd "$BIN" && git push);;
  *) echo "that did nothing. nothing was done";;
esac
