#!/bin/bash
BIN_HOME="${BIN_HOME:-"$( cd "$( dirname "${BASH_SOURCE[0]}" )" 2>&1 && cd ../ 2>&1 && pwd)"}"

source "$BIN_HOME/src/log.sh"

apply() {
  rm  "$HOME/.bashrc"
  cp "$BIN_HOME/templates/bashrc" "$HOME/.bashrc"
  sed -i '/BIN_HOME=/d' "$HOME/.bashrc"
  sed -i "1i BIN_HOME=\"$BIN_HOME\"" "$HOME/.bashrc"
  log "applied"
  exec bash
}

case "$1" in
  bashrc) "$VISUAL" "$BIN_HOME/templates/bashrc" && apply;;
  apply) apply;;
esac
