#!/bin/bash
BIN_HOME="${BIN_HOME:-"$( cd "$( dirname "${BASH_SOURCE[0]}" )" 2>&1 && cd ../ 2>&1 && pwd)"}"

source "$BIN_HOME/src/log.sh"

apply() {
  rm  "$HOME/.bashrc"
  cp "$BIN_HOME/templates/bashrc" "$HOME/.bashrc"
  sed -i '/BIN_HOME=/d' "$HOME/.bashrc"
  sed -i "1i BIN_HOME=\"$BIN_HOME\"" "$HOME/.bashrc"
  log "applied"
}

case "$1" in
  alias)
    [[ -z "$2" ]] && read -rp "name: " name
    name="${name:-"$2"}"
    [[ -z "$3" ]] && read -rp "command: " cmd
    cmd="${cmd:-"${@:3}"}"
    sed -i "/$name=/d" "$BIN_HOME/user/aliases"
    echo "alias $name='$cmd'" >> "$BIN_HOME/user/aliases"
    ;;
  # env) ;;
  # secret) ;;
  bashrc) "$VISUAL" "$BIN_HOME/templates/bashrc" && apply;;
  apply) apply;;
esac
