#!/bin/bash
# Bash Cheatsheet: https://devhints.io/bash
# source "${0%/*}/../src/core.sh";

# Flags
# NOTE: if a flag takes an argument you need to `shift 2`, otherwise just `shift`
# =====================================================================================================================

PARAMS=""
while (( "$#" )); do case "$1" in
  --edit|-e)
    EDIT="yes"
    shift
    ;;
  --)
    shift
    break
    ;;
  -*|--*)
    echo "Error: Unsupported flag $1" >&2
    exit 1
    ;;
  *)
    PARAMS="$PARAMS $1"
    shift
    ;;
esac; done
eval set -- "$PARAMS"

month() {
  local m=${1:-"$(date "%m")"}
  local dir="$LOG_HOME$(date +"/%Y/$1")"
  [[ -e "$dir" ]] || { echo "Nothing." && exit 1; }
  for day in "$dir/"*.md; do
    cat "$day"
    echo
  done
}

today() {
  local m="$LOG_HOME$(date +'/%Y/%m')"
  local d="$(date +'%d').md"
  [[ -e "$m" ]] || mkdir -p "$m"
  [[ -f "$m/$d" ]] || echo "[$(date +'%A - %m/%d')]" >> "$m/$d"
  echo "$m/$d"
}

[[ -n "$LOG_HOME" ]] || {
  echo "[INFO] source $HOME/.ENV"
  source "$HOME/.ENV"
}
[[ -n "$LOG_HOME" ]] || {
  read -n 1 -rp "LOG_HOME is not set. Would you like to export it in $HOME/.ENV? (y/N) " should_write
  echo "!"
  [[ $should_write =~ [Yy] ]] && {
    read -rp "Where would you like to store your notes? " dir
    echo "export LOG_HOME=\"$dir\" >> $HOME/.ENV"
    echo "export LOG_HOME=\"$dir\"" >> "$HOME/.ENV"
    source "$HOME/.ENV"
    exit 0
  }
  echo "Please manually add LOG_HOME to your ENV in order to use log"
  exit 1
}

case "$1" in
  today)
    echo
    cat "$(today)"
    echo
    ;;
  month)
    echo
    month "${2:-"$(date +'%m')"}"
    echo
    ;;
  *)
    if [[ -z "$EDIT" ]]; then
      read -rp $'new log entry:\n' entry
      echo "- $entry" >> "$(today)"
      echo
      cat "$(today)"
      echo
    else
      "$VISUAL" "$(today)"
    fi
    ;;
esac
