#!/bin/bash
# Bash Cheatsheet: https://devhints.io/bash
ROOT="${0%/*}"
source "$ROOT/../src/core.sh";

SITESPEED_RESULTS="$WINDOWS/Documents/ELCOnline"

case "$1" in
  test)
    read -rp "url: " url
    read -rp "basic auth (brand@password): " auth
    read -rp "number of tests: " times

    read -n 1 -rp "bypass akami? (y/n): " akami
    case "$akami" in
      Y|y) akami=1;;
      *) akami=0;;
    esac
    echo

    read -n 1 -rp "capture video? (y/n): " video
    case "$video" in
      Y|y) video=true;;
      *) video=false;;
    esac
    echo

    read -n 1 -rp "capture speed index? (y/n): " speed_index
    case "$speed_index" in
      Y|y) speed_index=true;;
      *) speed_index=false;;
    esac
    echo

    docker run --rm \
      -v "$SITESPEED_RESULTS":/sitespeed.io \
      sitespeedio/sitespeed.io:latest $url \
      -b chrome \
      --browsertime.chrome.args ignore-certificate-errors \
      --basicAuth $auth \
      --cookie BYPASS_AKAMAI="$akami" \
      --html.showAllWaterfallSummary \
      --video "$video" \
      --speedIndex "$speed_index" \
      --mobile \
      --network 3gfast \
      -n"$times"
    ;;
  view)
    PS3="which url: "
    select results in "$(ls "$SITESPEED_RESULTS/sitespeed-result")"; do
      PS3="what date: "
      select date in "$(ls "$SITESPEED_RESULTS/sitespeed-result/$results")"; do
        link=$(echo "file://$SITESPEED_RESULTS/sitespeed-result/$results/$date/index.html" | sed 's/\/c\//c:/')
        open_url "$link"
        exit 0
      done
    done
    ;;
  *) echo "that did nothing. nothing happened.";;
esac
