#!/bin/bash
BIN_HOME="${BIN_HOME:-"$( cd "$( dirname "${BASH_SOURCE[0]}" )" 2>&1 && cd ../ 2>&1 && pwd)"}"

source "$BIN_HOME/src/log.sh"

VIRO="$BIN_HOME/user/ENV"

# Flags
# NOTE: if a flag takes an argument you need to `shift 2`, otherwise just `shift`
# =====================================================================================================================

PARAMS=""
while (( "$#" )); do case "$1" in
  --secret)
    VIRO="$BIN_HOME/user/secret_ENV"
    shift;;
  --)
    shift
    break
    ;;
  -*|--*)
    log "Error: Unsupported flag $1" >&2
    exit 1
    ;;
  *)
    PARAMS="$PARAMS $1"
    shift
    ;;
esac; done
eval set -- "$PARAMS"

apply() {
  rm  "$HOME/.bashrc"
  cp "$BIN_HOME/templates/bashrc" "$HOME/.bashrc"
  sed -i '/BIN_HOME=/d' "$HOME/.bashrc"
  sed -i "1i BIN_HOME=\"$BIN_HOME\"" "$HOME/.bashrc"
  log "applied"
  exec bash
}

mkdir -p "$(dirname "$VIRO")" && touch "$VIRO"
case "$1" in
  bashrc) "$VISUAL" "$BIN_HOME/templates/bashrc" && apply;;
  apply) apply;;
  ls|show|view) sed -e 's/export/[viro]/' -e 's/=/~/' -e "s/'//g" < "$VIRO" | column -t -s~;;
  edit) "$VISUAL" "$VIRO" && exec bash;;
  a|add|create|new)
    [[ -z "$2" ]] && read -rp "name: " name
    name="${name:-"$2"}"
    name="${name^^}" # ALL_CAPS
    [[ -z "$3" ]] && read -rp "value: " value
    value="${value:-"${@:3}"}"

    sed -i "/export $name=/d" "$VIRO"
    echo "export $name='$value'" >> "$VIRO"
    log "added: $(grep "export $name" "$VIRO")"
    exec bash
    ;;
  r|rm|remove)
    [[ -z "$2" ]] && name="$(sed -e 's/=./ /' < "$VIRO" | awk '{print $2}' | fzf)"
    name="${name:-"$2"}"
    [[ -z "$name" ]] && log "No ENV have been removed" && exit 1
    name="${name:-"$2"}"
    name="${name^^}" # ALL_CAPS

    log "removed: $( grep "export $name" "$VIRO" )"
    sed -i "/export $name=/d" "$VIRO"
    exec bash
    ;;
  *) man -l "$BIN_HOME/.manpages/viro.1"
esac
