.TH BIN 1 "09 Sept 2019" "1.0" "bin"
.SH NAME
bin \- a bash executable manager
.SH SYNOPSIS
bin
.B [ls|show|view]
.br
bin
.B [a|add|create|new|edit]
.I name
.br
bin
.B [r|rm|remove]
.I name
.br
bin
.B rename
.I old-name
.I new-name
.SH DESCRIPTION
bin makes adding and removing aliases simple
.SH ENVIRONMENT
.TP
.B BIN_HOME
path where bin manages its internal files
.SH FILES
.TP
.B $BIN_HOME/bins
where bin stores your executable shell files
.SH AUTHOR
Talon Poole (hello@talon.computer)
.SH COPYWRITE
Copyright \(co 2019 Talon Poole.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
.br
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
