VIRO_HOME="/c/Users/tpoole/Documents/GitHub/bin"
[[ -f "$VIRO_HOME/user/ENV" ]] && source "$VIRO_HOME/user/ENV";
[[ -f "$VIRO_HOME/user/secret_ENV" ]] && source "$VIRO_HOME/user/secret_ENV";
[[ -f "$VIRO_HOME/user/aliases" ]] && source "$VIRO_HOME/user/aliases";

source "$VIRO_HOME/src/host/wsl-ubuntu.sh"
source "$VIRO_HOME/src/log.sh"

packages() {
  log "ensuring packages are available"
  ensure curl
  ensure git
  ensure openssh-client
  ensure tmux
  nvim -v | grep -q -E "NVIM v0.3.*" || {
    log "adding neovim repo and upgrading"
    repo ppa:neovim-ppa/stable;
    apt update;
    apt upgrade -y;
    ensure neovim;
  }
  ensure python-dev;
  ensure python-pip;
  ensure python3-dev;
  ensure python3-pip;
  ensure python-neovim;
  ensure python3-neovim;
  ensure tig
  is_installed docker-ce || {
    log "adding docker-ce repo and installing"
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -;
    apt-key fingerprint 0EBFCD88;
    repo "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable";
    ensure docker-ce;
  }
  ensure docker-compose
}

[[ -s "$NVM_DIR/nvm.sh" ]] && \. "$NVM_DIR/nvm.sh"
[[ -n "$PS1" ]] && [[ -s "$BASE16_SHELL/profile_helper.sh" ]] && eval "$("$BASE16_SHELL/profile_helper.sh")";
[[ -f "$HOME/.fzf.bash" ]] && source "$HOME/.fzf.bash";
[[ -z "$TMUX"  ]] && {
  packages
  ssh-keygen -q -N "" < /dev/zero > /dev/null
  clone https://github.com/chriskempson/base16-shell.git "$BASE16_SHELL"
  download "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim" "$HOME/.local/share/nvim/site/autoload/plug.vim"
  mkdir -p "$HOME/.config/nvim/" && cp "$VIRO_HOME/templates/init.vim" "$HOME/.config/nvim/init.vim"
  clone https://github.com/tmux-plugins/tpm "$HOME/.tmux/plugins/tpm"
  cp "$VIRO_HOME/templates/tmux.conf" "$HOME/.tmux.conf"
  clone https://github.com/nvm-sh/nvm.git "$NVM_DIR"
  tmux attach || exec tmux new-session
}
