#!/bin/bash
BIN_HOME="${BIN_HOME:-"$( cd "$( dirname "${BASH_SOURCE[0]}" )" 2>&1 && cd ../ 2>&1 && pwd)"}"

# Flags
# NOTE: if a flag takes an argument you need to `shift 2`, otherwise just `shift`
# =====================================================================================================================

PARAMS=""
while (( "$#" )); do case "$1" in
  --)
    shift
    break
    ;;
  -*|--*)
    echo "Error: Unsupported flag $1" >&2
    exit 1
    ;;
  *)
    PARAMS="$PARAMS $1"
    shift
    ;;
esac; done
eval set -- "$PARAMS"

case "$1" in
  *)
    echo
    echo "this bin has no functionality yet"
    echo
    echo "    bin edit $( basename ${BASH_SOURCE[0]} )"
    echo
    ;;
esac
