.TH ALIEN 1 "09 Sept 2019" "1.0" "alien"
.SH NAME
alien \- an alias manager
.SH SYNOPSIS
alien
.B ls
.br
alien
.B create
.I name
.I value
.br
alien
.B edit
.I name
.br
alien
.B rm
.I name
.I value
.SH DESCRIPTION
alien makes adding and removing aliases simple
.SH OPTIONS
.TP
.B --secret
saves aliases to a seperate secret_aliases file
.SH ENVIRONMENT
.TP
.B VIRO_HOME
path where alien manages its internal files
.SH FILES
.TP
.B $VIRO_HOME/user/aliases
where alien stores your public aliases
.TP
.B $VIRO_HOME/user/secret_aliases
where alien stores your secret aliases
.SH AUTHOR
Talon Poole (hello@talon.computer)
.SH COPYWRITE
Copyright \(co 2019 Talon Poole.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
.br
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
