.TH BIN 1 "09 Sept 2019" "1.0" "bin"
.SH NAME
bin \- a bash executable manager
.SH SYNOPSIS
bin
.B ls
.br
bin
.B create
.I name
.br
bin
.B edit
.I name
.br
bin
.B rm
.I name
.br
bin
.B rename
.I old-name
.I new-name
.SH DESCRIPTION
bin makes managing executable bash files simple
.SH OPTIONS
.TP
--core
.RS
modify core viro bins.
.B Use with caution!
but feel free to contribute! :)
.SH FILES
.TP
.B $VIRO_HOME/user/bins
where bin stores your executable shell files
.SH AUTHOR
Talon Poole (hello@talon.computer)
.SH COPYWRITE
Copyright \(co 2019 Talon Poole.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
.br
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
