.TH PAT 1 "30 Sept 2019" "1.0" "pat"
.SH NAME
pat \- a PATH manager
.SH SYNOPSIS
pat
.B ls
.br
pat
.B add
.I directory
.br
pat
.B edit
.br
pat
.B rm
.I directory
.SH DESCRIPTION
pat makes adding and removing PATHs simple
.SH ENVIRONMENT
.TP
.B VIRO_HOME
path where pat manages its internal files
.SH FILES
.TP
.B $VIRO_HOME/user/PATH
where pat stores your PATH
.SH AUTHOR
Talon Poole (hello@talon.computer)
.SH COPYWRITE
Copyright \(co 2019 Talon Poole.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
.br
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
