.TH VIRO 1 "09 Sept 2019" "1.0" "viro"
.SH NAME
viro \- an environment manager
.SH SYNOPSIS
viro
.B install
.LP
viro
.B refresh
.LP
viro
.B boot
.LP
viro
.B [env|alias|path]
ls
.LP
viro
.B [env|alias|path]
edit
.LP
viro
.B [env|alias|path]
add
.I name
.I value
.LP
viro
.B [env|alias|path]
rm
.I name
.I value
.LP
viro
.B [env|alias|path]
has
.I name
.LP
.SH DESCRIPTION
viro makes managing your environment simple
.SH ENVIRONMENT
.TP
.B VIRO_HOME
path where viro manages its internal files
.SH FILES
.TP
.B $VIRO_HOME/user/ENV
your environment variables
.TP
.B $VIRO_HOME/user/aliases
your aliases
.TP
.B $VIRO_HOME/user/PATH
your PATH
.TP
.B $VIRO_HOME/user/boot.sh
for startup script stuff
.TP
.B $VIRO_HOME/user/bins
the folder with any bins you've created
.SH AUTHOR
Talon Poole (hello@talon.computer)
.SH COPYWRITE
Copyright \(co 2019 Talon Poole.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
.LP
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
