.Dd 2019
.Dt VIRO 1
.
.Sh NAME
.
.Nm viro
.Nd an environment manager
.
.Sh SYNOPSIS
.
.Nm viro
.Cm env
.Op ls
.Op set Ar name Ar value
.Op get Ar name
.Op rm Ar name
.Op has Ar name
.
.Nm viro
.Cm path
.Op ls
.Op add Ar dir
.Op rm Ar dir
.Op has Ar dir
.
.Nm viro
.Cm fn
.Op new Ar name
.Op edit Ar name
.Op cp Ar name Ar new
.Op rm Ar name
.
.Sh DESCRIPTION
.
viro allows you to swiftly manage environment variables and create shell functions/executables
by providing a thin wrapper around existing shell utilities.
.
.Sh EXAMPLES
.Bl -tag -width 6n
.
.It viro env set NODE_ENV development
set any environment variable
.
.It viro path add ~/.bin
add directories to your PATH
.
.It viro fn new my-shell-fn
create a shell function
.
.It viro fn edit my-shell-fn
edit it
.
.Sh ENVIRONMENT
.Bl -tag -width 6n
.
.It VIRO_SRC
Where the viro source files live
.
.It VIRO_USER
Where your personal viro configuration files live. Default: $HOME/.viro
.
.Sh FILES
.Bl -tag -width 6n
.
.It VIRO_USER/ENV
where viro stores your env variables
.
.It VIRO_USER/PATH
where viro stores your PATH
.
.It VIRO_USER/functions
where viro stores your shell functions
.
.Sh BUGS
.Sy https://github.com/talon/viro/issues
.
.Sh AUTHORS
Talon Poole <hello@talon.computer>
